version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: powell_postgres
    restart: unless-stopped
    ports:
      - "7894:5432"
    environment:
      POSTGRES_USER: powellhomeschool
      POSTGRES_PASSWORD: "@powe!!homeschool2025"
      POSTGRES_DB: powellhomeschool
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d


  redis:
    image: redis:8
    container_name: powell_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
